name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - name: Maven build
      run: |
        mvn --batch-mode -DskipTests package

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/spin-tools-linux*

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - name: Maven build
      run: |
        mvn --batch-mode -DskipTests package

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/spin-tools-windows*

  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - name: Maven build
      run: |
        mvn --batch-mode -DskipTests package

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/spin-tools-macos*

