name: Release Build

on:
  push:
    tags: [ '*' ]

jobs:
  release:

    runs-on: ubuntu-latest
    container:
        image: maccasoft/build-agent

    steps:
    - uses: actions/checkout@v3

    - name: Maven build
      run: |
        Xvfb :1 -ac -screen 0 1280x1024x8 -nolisten tcp &
        mvn --batch-mode -f build/pom.xml package

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/linux/target/spin-tools-linux*
          build/windows/target/spin-tools-windows*
          build/macosx/target/spin-tools-macos*

    - name: Create Tests Summary
      uses: test-summary/action@dist
      with:
        paths: target/surefire-reports/**/*.xml
      if: always()
