name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          target/spin-tools*

