name: Verify

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'

    - name: Maven verify
      run: |
        xvfb-run --auto-servernum mvn --batch-mode verify

    - name: Create Tests Summary
      uses: test-summary/action@dist
      with:
        paths: modules/spin-tools/target/surefire-reports/**/*.xml
      if: always()

