name: Verify

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  verify:

    runs-on: ubuntu-latest
    container:
        image: maccasoft/build-agent

    steps:
    - uses: actions/checkout@v3

    - name: Maven verify
      run: |
        Xvfb :1 -ac -screen 0 1280x1024x8 -nolisten tcp &
        mvn --batch-mode verify

    - name: Create Tests Summary
      uses: test-summary/action@dist
      with:
        paths: target/surefire-reports/**/*.xml
      if: always()
